navigate:
  ros__parameters:
    plugins:
      - navigate_bt_node
    waypoints: ["charging_station", "unload_zone", "shelf_1", "shelf_2", "shelf_3", "shelf_4"]
    waypoint_coordinates:
      charging_station: [-2.0, -0.5, 0.0]
      unload_zone: [2.0, 0.5, 0.0]
      shelf_1: [0.5, 2.0, 0.0]
      shelf_2: [-0.5, 2.0, 0.0]
      shelf_3: [0.5, -2.0, 0.0]
      shelf_4: [-0.5, -2.0, 0.0]

transport:
  ros__parameters:
    plugins:
      - lower_fork_bt_node
      - approach_pallet_bt_node
      - raise_fork_bt_node
      - navigate_bt_node
      - leave_pallet_bt_node
    waypoints: ["charging_station", "unload_zone", "shelf_1", "shelf_2", "shelf_3", "shelf_4"]
    waypoint_coordinates:
      charging_station: [-2.0, -0.5, 0.0]
      unload_zone: [2.0, 0.5, 0.0]
      shelf_1: [0.5, 2.0, 0.0]
      shelf_2: [-0.5, 2.0, 0.0]
      shelf_3: [0.5, -2.0, 0.0]
      shelf_4: [-0.5, -2.0, 0.0]

recharge:
  ros__parameters:
    plugins:
      - recharge_bt_node