navigate:
  ros_parameters:
    - navigate_bt_node
    waypoints: ["charging_station", "unload_zone", "reol_1", "reol_2", "reol_3", reol_4]
    waypoint_coordinates:
      charging_station: [-2.0, -0.5, 0.0]
      unload_zone: [2.0, 0.5, 0.0]
      reol_1: [0.5, 2.0, 0.0]
      reol_2: [-0.5, 2.0, 0.0]
      reol_3: [0.5, -2.0, 0.0]
      reol_4: [-0.5, -2.0, 0.0]

transport:
  ros_parameters:
    plugins:
      - lower_fork_bt_node
      - approach_pallet_bt_node
      - lift_fork_bt_node
      - navigate_bt_node
    waypoints: ["charging_station", "unload_zone", "reol_1", "reol_2", "reol_3", reol_4]
    waypoint_coordinates:
      charging_station: [-2.0, -0.5, 0.0]
      unload_zone: [2.0, 0.5, 0.0]
      reol_1: [0.5, 2.0, 0.0]
      reol_2: [-0.5, 2.0, 0.0]
      reol_3: [0.5, -2.0, 0.0]
      reol_4: [-0.5, -2.0, 0.0]

recharge:
  ros_parameters:
    plugins:
      - recharge_bt_node
